---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # force argocd to delete the kubernetes app first and then removes it from the argocd

spec:
  project: default
  source:
    repoURL: https://github.com/antonputra/lesson-158.git
    targetRevision: HEAD # the heads points to your main branches latest commit
    path: my-app # the path to your manifest files in the repo

  destination:
    server: https://kubernetes.default.svc
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true